/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static admin.Admin_GUI.cont;

/**
 *
 * @author Hady Ahmed
 */
public class Show_Saved_book extends javax.swing.JFrame {

    /**
     * Creates new form Show_Saved_book
     */
    public Show_Saved_book() {
        initComponents();
    }
    public void setData(String name,String id,String authe,String year,int copies,String category){
        name_f.setText(name);
        id_f.setText(id);
        aouther_f.setText(authe);
        proyear_f.setText(year);
        copy_f.setText(String.valueOf(copies));
        cat_f.setText(category);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator55 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jSeparator57 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        aouther_f = new javax.swing.JTextField();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        name_f = new javax.swing.JTextField();
        proyear_f = new javax.swing.JTextField();
        jSeparator62 = new javax.swing.JSeparator();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        id_f = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat_f = new javax.swing.JTextField();
        jSeparator63 = new javax.swing.JSeparator();
        copy_f = new javax.swing.JTextField();
        jSeparator64 = new javax.swing.JSeparator();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Saved Book Data ");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 190, -1));
        jPanel10.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 450, 10));

        jLabel41.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Author");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, 20));
        jPanel10.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 450, 10));

        jLabel42.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Title");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 60, -1));

        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("ID");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 30, -1));

        aouther_f.setEditable(false);
        aouther_f.setBackground(new java.awt.Color(17, 9, 50));
        aouther_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        aouther_f.setForeground(new java.awt.Color(255, 255, 255));
        aouther_f.setText("password");
        aouther_f.setToolTipText("password");
        aouther_f.setBorder(null);
        aouther_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        aouther_f.setOpaque(false);
        jPanel10.add(aouther_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 210, 20));
        jPanel10.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 450, 10));
        jPanel10.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 10));
        jPanel10.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 10));
        jPanel10.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 10));

        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Category");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, -1));

        name_f.setEditable(false);
        name_f.setBackground(new java.awt.Color(17, 9, 50));
        name_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        name_f.setForeground(new java.awt.Color(255, 255, 255));
        name_f.setText("The First Name");
        name_f.setToolTipText("The First Name");
        name_f.setBorder(null);
        name_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name_f.setOpaque(false);
        jPanel10.add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 210, 20));

        proyear_f.setEditable(false);
        proyear_f.setBackground(new java.awt.Color(17, 9, 50));
        proyear_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        proyear_f.setForeground(new java.awt.Color(255, 255, 255));
        proyear_f.setText("Address");
        proyear_f.setToolTipText("Address");
        proyear_f.setBorder(null);
        proyear_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        proyear_f.setOpaque(false);
        jPanel10.add(proyear_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 210, 20));
        jPanel10.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 450, 10));

        jButton31.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/menu 1.png"))); // NOI18N
        jButton31.setText("      Main Menu");
        jButton31.setToolTipText("To Main Menu");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setDefaultCapable(false);
        jButton31.setFocusPainted(false);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/menu 2.png"))); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        jButton32.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/logout 1.png"))); // NOI18N
        jButton32.setText("Logout");
        jButton32.setToolTipText("Logout");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setDefaultCapable(false);
        jButton32.setFocusPainted(false);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/logout 2.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        jButton33.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/home 1.png"))); // NOI18N
        jButton33.setText("Home");
        jButton33.setToolTipText("Home");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setDefaultCapable(false);
        jButton33.setFocusPainted(false);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/home 2.png"))); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        jLabel45.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Production year");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, -1));

        id_f.setEditable(false);
        id_f.setBackground(new java.awt.Color(17, 9, 50));
        id_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        id_f.setForeground(new java.awt.Color(255, 255, 255));
        id_f.setText("ID");
        id_f.setToolTipText("ID");
        id_f.setBorder(null);
        id_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_f.setOpaque(false);
        jPanel10.add(id_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 210, 20));

        jLabel46.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Number of Copies");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/diff logo.png"))); // NOI18N
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 80));

        cat_f.setEditable(false);
        cat_f.setBackground(new java.awt.Color(17, 9, 50));
        cat_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cat_f.setForeground(new java.awt.Color(255, 255, 255));
        cat_f.setText("Email");
        cat_f.setToolTipText("Email");
        cat_f.setBorder(null);
        cat_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cat_f.setOpaque(false);
        jPanel10.add(cat_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 210, 20));
        jPanel10.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 450, 10));

        copy_f.setEditable(false);
        copy_f.setBackground(new java.awt.Color(17, 9, 50));
        copy_f.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        copy_f.setForeground(new java.awt.Color(255, 255, 255));
        copy_f.setText("Phone number");
        copy_f.setToolTipText("Phone number");
        copy_f.setBorder(null);
        copy_f.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        copy_f.setOpaque(false);
        jPanel10.add(copy_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 210, 20));
        jPanel10.add(jSeparator64, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 450, 10));

        jButton13.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/botton.png"))); // NOI18N
        jButton13.setText("Back");
        jButton13.setToolTipText("Back to the previous page");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/botton2_1.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/lefte.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/lib textuers/right.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 740, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        cont.Saved_book.setVisible(false);
        cont.Admin.setVisible(true);
        cont.Admin.setResizable(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        cont.Saved_book.setVisible(false);
        cont.log.setVisible(true);
        cont.log.setResizable(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        cont.Saved_book.setVisible(false);
        cont.home.setVisible(true);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        cont.Saved_book.setVisible(false);
        cont.add_book.setVisible(true);
        cont.add_user.setResizable(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aouther_f;
    private javax.swing.JTextField cat_f;
    private javax.swing.JTextField copy_f;
    private javax.swing.JTextField id_f;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JTextField name_f;
    private javax.swing.JTextField proyear_f;
    // End of variables declaration//GEN-END:variables
}
